classdef sdzpk < zpk & sdlti
    
    methods (Access = public)
        function obj = sdzpk(varargin)
            if nargin == 1 && isa(varargin{1},'lti')
                if ~isa(varargin{1},'zpk')
                    old = zpk(varargin{1});
                else
                    old = varargin{1};
                end
                args = {old.Z old.P old.K old.Ts ...
                    'DisplayFormat'    old.DisplayFormat...
                    'Variable'         old.Variable...
                    'IODelay'          old.IODelay...
                    'InputDelay'       old.InputDelay...
                    'OutputDelay'      old.OutputDelay...
                    'TimeUnit'         old.TimeUnit...
                    'InputName'        old.InputName...
                    'InputUnit'        old.InputUnit...
                    'InputGroup'       old.InputGroup...
                    'OutputName'       old.OutputName...
                    'OutputUnit'       old.OutputUnit...
                    'OutputGroup'      old.OutputGroup...
                    'Name'             old.Name...
                    'Notes'            old.Notes...
                    'UserData'         old.UserData};
                %args = args{:};                
            else
                args = varargin;
            end
            obj = obj@zpk(args{:});
        end
        tsys = ctranspose(sys);
        sys = delay2z(sys);
        sysr = minreal(sys,tol);
        F = minreals(F,tol);
        FP = setpoles(F,p);
        F = symmetr(F,type,tol);
        F = z2zeta(F,tol);
    end       
end

